# Generated by Django 4.0.6 on 2022-10-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('country', models.CharField(choices=[('USA', 'USA'), ('China', 'China'), ('Russia', 'Russia'), ('Japan', 'Japan'), ('Autralia', 'Australia')], max_length=50)),
                ('age', models.IntegerField()),
                ('ip', models.IntegerField()),
                ('job', models.CharField(choices=[('Doctor', 'Doctor'), ('Teacher', 'Teacher'), ('Mechanic', 'Mechanic'), ('Plumber', 'Plumber'), ('Freelancer', 'Freelancer'), ('Developer', 'Developer'), ('Accountant', 'Accountant'), ('Carpenter', 'Carpenter'), ('Sporter', 'Sporter'), ('Unimployment', "Haven't had yet")], default='Unimployment', max_length=50)),
            ],
        ),
    ]
