# Generated by Django 4.1.1 on 2022-10-01 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("HOME", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visa",
            name="ip",
            field=models.CharField(max_length=10, null=True),
        ),
    ]
